name: Deploy Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Composer Install Dependencies
      uses: php-actions/composer@v6
      with:
        command: composer install

      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3.0
        with:
        # Deploy vars 
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
          WPE_ENV: jillswpedev
          # Deploy Options
          SRC_PATH: "wp-content/"
          REMOTE_PATH: "wp-content/"
          PHP_LINT: TRUE
          FLAGS: -azvr --inplace --delete-after --exclude=".*" --exclude-from=ignorefile.txt
          CACHE_CLEAR: TRUE
