name: Deploy Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACF: ${{ secrets.ACF_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .env
      - run: |
          rm .env
          touch .env
          echo ${{ env.ACF }}
          echo ${{ env.ACF }} >> .env

      - name: Composer Install Dependencies
        uses: php-actions/composer@v6

      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3.0
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: jillswpedev
          # Deploy Options
          SRC_PATH: "wp-content/"
          REMOTE_PATH: "wp-content/"
          PHP_LINT: TRUE
          FLAGS: -azvr --inplace --delete-after --exclude=".*" --exclude-from=ignorefile.txt
          CACHE_CLEAR: TRUE
